import mongoose from "mongoose";
import Recipe from "./models/Recipe";

const MONGO_URI =
  process.env.MONGO_URI || "mongodb://localhost:27017/kyapakaon";

const recipes = [
  // ============ RICE DISHES ============
  {
    name: "Chicken Biryani",
    description:
      "Fragrant basmati rice layered with spiced chicken, fried onions, saffron, and fresh herbs in a sealed pot.",
    ingredients: [
      "basmati rice",
      "chicken",
      "yogurt",
      "onions",
      "tomatoes",
      "ginger-garlic paste",
      "garam masala",
      "turmeric",
      "chili powder",
      "saffron",
      "mint",
      "coriander",
      "oil",
      "salt",
    ],
    cuisine: "Both",
    category: "Main Course",
    cookingTime: 90,
    servings: 6,
    spiceLevel: 2,
  },
  {
    name: "Mutton Biryani",
    description:
      "Slow-cooked mutton pieces with aromatic basmati rice, layered with caramelized onions and saffron milk.",
    ingredients: [
      "basmati rice",
      "mutton",
      "yogurt",
      "onions",
      "tomatoes",
      "ginger-garlic paste",
      "garam masala",
      "turmeric",
      "chili powder",
      "saffron",
      "mint",
      "coriander",
      "oil",
      "salt",
    ],
    cuisine: "Both",
    category: "Main Course",
    cookingTime: 120,
    servings: 6,
    spiceLevel: 2,
  },
  {
    name: "Hyderabadi Biryani",
    description:
      "A royal Hyderabadi-style biryani with marinated meat, fried onions, saffron, and slow-cooked on dum.",
    ingredients: [
      "basmati rice",
      "meat",
      "fried onions",
      "yogurt",
      "saffron",
      "mint",
      "coriander",
      "cardamom",
      "cloves",
      "cinnamon",
      "bay leaves",
      "ginger-garlic paste",
      "chili powder",
      "oil",
      "salt",
    ],
    cuisine: "Indian",
    category: "Main Course",
    cookingTime: 120,
    servings: 6,
    spiceLevel: 2,
  },
  {
    name: "Sindhi Biryani",
    description:
      "A bold, tangy biryani from Sindh with potatoes, plums, and an extra kick of green chilies.",
    ingredients: [
      "basmati rice",
      "meat",
      "potatoes",
      "yogurt",
      "tomatoes",
      "green chilies",
      "aloo bukhara",
      "onions",
      "ginger-garlic paste",
      "garam masala",
      "turmeric",
      "coriander",
      "mint",
      "oil",
      "salt",
    ],
    cuisine: "Pakistani",
    category: "Main Course",
    cookingTime: 100,
    servings: 6,
    spiceLevel: 3,
  },
  {
    name: "Pulao",
    description:
      "A light, aromatic rice dish cooked in flavored broth with whole spices and tender meat or vegetables.",
    ingredients: [
      "basmati rice",
      "meat",
      "onions",
      "cardamom",
      "cloves",
      "cinnamon",
      "bay leaves",
      "cumin",
      "broth",
      "oil",
      "salt",
    ],
    cuisine: "Both",
    category: "Main Course",
    cookingTime: 45,
    servings: 4,
    spiceLevel: 1,
  },
  {
    name: "Tehri",
    description:
      "A comforting vegetarian rice dish with potatoes, turmeric, and simple spices — everyday home cooking.",
    ingredients: [
      "basmati rice",
      "potatoes",
      "turmeric",
      "cumin",
      "onions",
      "green chilies",
      "oil",
      "salt",
    ],
    cuisine: "Both",
    category: "Main Course",
    cookingTime: 35,
    servings: 4,
    spiceLevel: 1,
  },
  {
    name: "Tahari",
    description:
      "A simple, turmeric-yellow rice and meat dish popular for its no-fuss flavor and home-style warmth.",
    ingredients: [
      "basmati rice",
      "meat",
      "turmeric",
      "onions",
      "garlic",
      "cumin",
      "oil",
      "salt",
    ],
    cuisine: "Pakistani",
    category: "Main Course",
    cookingTime: 50,
    servings: 4,
    spiceLevel: 1,
  },

  // ============ CURRIES (MEAT) ============
  {
    name: "Butter Chicken",
    description:
      "Tandoori-style chicken pieces swimming in a luscious tomato-butter sauce with a touch of cream.",
    ingredients: [
      "chicken",
      "tomato puree",
      "butter",
      "cream",
      "garam masala",
      "kasuri methi",
      "ginger-garlic paste",
      "chili powder",
      "sugar",
      "oil",
      "salt",
    ],
    cuisine: "Indian",
    category: "Main Course",
    cookingTime: 50,
    servings: 4,
    spiceLevel: 1,
  },
  {
    name: "Chicken Karahi",
    description:
      "A fiery tomato-based chicken curry cooked in a traditional wok, bursting with fresh ginger and green chilies.",
    ingredients: [
      "chicken",
      "tomatoes",
      "ginger",
      "garlic",
      "green chilies",
      "coriander",
      "cumin",
      "oil",
      "salt",
    ],
    cuisine: "Pakistani",
    category: "Main Course",
    cookingTime: 45,
    servings: 4,
    spiceLevel: 3,
  },
  {
    name: "Nihari",
    description:
      "A slow-cooked beef stew with rich, spiced gravy thickened with flour, traditionally served at dawn.",
    ingredients: [
      "beef shank",
      "flour",
      "ginger",
      "garlic",
      "garam masala",
      "bone marrow",
      "onions",
      "chili powder",
      "coriander",
      "oil",
      "salt",
    ],
    cuisine: "Pakistani",
    category: "Main Course",
    cookingTime: 240,
    servings: 6,
    spiceLevel: 3,
  },
  {
    name: "Korma",
    description:
      "A rich, creamy curry of tender meat slow-cooked in yogurt, cream, and a paste of fried onions and nuts.",
    ingredients: [
      "meat",
      "yogurt",
      "cream",
      "cashews",
      "fried onions",
      "cardamom",
      "cloves",
      "cinnamon",
      "ginger-garlic paste",
      "oil",
      "salt",
    ],
    cuisine: "Both",
    category: "Main Course",
    cookingTime: 60,
    servings: 4,
    spiceLevel: 1,
  },
  {
    name: "Rogan Josh",
    description:
      "A vibrant Kashmiri lamb curry with deep red color from Kashmiri chili and warm fennel undertones.",
    ingredients: [
      "lamb",
      "yogurt",
      "kashmiri chili",
      "fennel powder",
      "ginger",
      "garlic",
      "onions",
      "cardamom",
      "cloves",
      "oil",
      "salt",
    ],
    cuisine: "Indian",
    category: "Main Course",
    cookingTime: 75,
    servings: 4,
    spiceLevel: 2,
  },
  {
    name: "Saag Gosht",
    description:
      "Tender meat chunks simmered with pureed mustard greens and spinach, finished with garlic and ginger.",
    ingredients: [
      "meat",
      "spinach",
      "mustard greens",
      "garlic",
      "ginger",
      "onions",
      "green chilies",
      "garam masala",
      "oil",
      "salt",
    ],
    cuisine: "Both",
    category: "Main Course",
    cookingTime: 70,
    servings: 4,
    spiceLevel: 2,
  },
  {
    name: "Haleem",
    description:
      "A thick, hearty stew of slow-cooked wheat, lentils, and shredded meat, topped with fried onions and ghee.",
    ingredients: [
      "wheat",
      "chana dal",
      "masoor dal",
      "meat",
      "ghee",
      "fried onions",
      "ginger-garlic paste",
      "garam masala",
      "turmeric",
      "oil",
      "salt",
    ],
    cuisine: "Pakistani",
    category: "Main Course",
    cookingTime: 300,
    servings: 8,
    spiceLevel: 2,
  },
  {
    name: "Payaya",
    description:
      "A rich, gelatinous goat trotters stew slow-cooked with aromatic spices — a traditional winter delicacy.",
    ingredients: [
      "goat trotters",
      "garlic",
      "ginger",
      "onions",
      "cardamom",
      "cinnamon",
      "bay leaves",
      "chili powder",
      "turmeric",
      "oil",
      "salt",
    ],
    cuisine: "Pakistani",
    category: "Main Course",
    cookingTime: 180,
    servings: 4,
    spiceLevel: 2,
  },

  // ============ VEGETARIAN DISHES ============
  {
    name: "Chana Masala",
    description:
      "Hearty chickpeas simmered in a tangy, spiced tomato sauce with a squeeze of lemon.",
    ingredients: [
      "chickpeas",
      "tomatoes",
      "onions",
      "cumin",
      "coriander",
      "garam masala",
      "ginger-garlic paste",
      "chili powder",
      "lemon",
      "oil",
      "salt",
    ],
    cuisine: "Both",
    category: "Main Course",
    cookingTime: 35,
    servings: 4,
    spiceLevel: 2,
  },
  {
    name: "Palak Paneer",
    description:
      "Cubes of soft paneer cheese floating in a velvety, spiced spinach puree.",
    ingredients: [
      "spinach",
      "paneer",
      "garlic",
      "cream",
      "garam masala",
      "onions",
      "ginger",
      "cumin",
      "oil",
      "salt",
    ],
    cuisine: "Indian",
    category: "Main Course",
    cookingTime: 40,
    servings: 4,
    spiceLevel: 1,
  },
  {
    name: "Aloo Gobi",
    description:
      "Tender potatoes and cauliflower florets tossed with turmeric and cumin seeds in a dry-style curry.",
    ingredients: [
      "potatoes",
      "cauliflower",
      "turmeric",
      "cumin",
      "onions",
      "tomatoes",
      "green chilies",
      "coriander",
      "oil",
      "salt",
    ],
    cuisine: "Indian",
    category: "Side Dish",
    cookingTime: 30,
    servings: 4,
    spiceLevel: 2,
  },
  {
    name: "Baingan Bharta",
    description:
      "Smoky roasted eggplant mashed with onions, tomatoes, and green chilies for a rustic, bold flavor.",
    ingredients: [
      "eggplant",
      "tomatoes",
      "onions",
      "green chilies",
      "garlic",
      "cumin",
      "coriander",
      "oil",
      "salt",
    ],
    cuisine: "Indian",
    category: "Side Dish",
    cookingTime: 40,
    servings: 4,
    spiceLevel: 2,
  },
  {
    name: "Bhindi Masala",
    description:
      "Crispy okra stir-fried with onions, turmeric, and cumin — a beloved everyday vegetable dish.",
    ingredients: [
      "okra",
      "onions",
      "turmeric",
      "cumin",
      "tomatoes",
      "chili powder",
      "oil",
      "salt",
    ],
    cuisine: "Both",
    category: "Side Dish",
    cookingTime: 25,
    servings: 4,
    spiceLevel: 2,
  },

  // ============ BBQ & STREET FOOD ============
  {
    name: "Seekh Kebab",
    description:
      "Juicy minced meat skewers seasoned with fresh herbs and warm spices, grilled over charcoal.",
    ingredients: [
      "ground meat",
      "onions",
      "green chilies",
      "garam masala",
      "coriander",
      "cumin",
      "ginger",
      "garlic",
      "oil",
      "salt",
    ],
    cuisine: "Pakistani",
    category: "Appetizer",
    cookingTime: 25,
    servings: 4,
    spiceLevel: 2,
  },
  {
    name: "Chapli Kebab",
    description:
      "Flat, spiced meat patties studded with pomegranate seeds and coriander seeds, pan-fried to a crisp.",
    ingredients: [
      "ground beef",
      "tomatoes",
      "coriander seeds",
      "pomegranate seeds",
      "onions",
      "green chilies",
      "cumin",
      "egg",
      "oil",
      "salt",
    ],
    cuisine: "Pakistani",
    category: "Appetizer",
    cookingTime: 30,
    servings: 4,
    spiceLevel: 3,
  },
  {
    name: "Shami Kebab",
    description:
      "Silky-smooth lentil and meat patties, lightly spiced and pan-fried until golden — perfect with chutney.",
    ingredients: [
      "ground meat",
      "chana dal",
      "egg",
      "onions",
      "ginger",
      "garlic",
      "garam masala",
      "green chilies",
      "coriander",
      "oil",
      "salt",
    ],
    cuisine: "Both",
    category: "Appetizer",
    cookingTime: 45,
    servings: 6,
    spiceLevel: 2,
  },
  {
    name: "Samosa",
    description:
      "Golden, crispy pastry triangles stuffed with spiced potatoes and peas, perfect as a tea-time snack.",
    ingredients: [
      "flour",
      "potatoes",
      "peas",
      "cumin",
      "coriander",
      "green chilies",
      "garam masala",
      "onions",
      "oil",
      "salt",
    ],
    cuisine: "Both",
    category: "Street Food",
    cookingTime: 45,
    servings: 8,
    spiceLevel: 2,
  },
  {
    name: "Pakora",
    description:
      "Crispy, golden fritters made from gram flour batter and mixed vegetables — the ultimate rainy-day snack.",
    ingredients: [
      "gram flour",
      "onions",
      "potatoes",
      "spinach",
      "green chilies",
      "cumin",
      "chili powder",
      "oil",
      "salt",
    ],
    cuisine: "Both",
    category: "Street Food",
    cookingTime: 20,
    servings: 4,
    spiceLevel: 2,
  },
  {
    name: "Gol Gappa",
    description:
      "Hollow crispy puris filled with spiced tamarind water, chickpeas, and potatoes — an explosion of flavors.",
    ingredients: [
      "semolina",
      "flour",
      "tamarind",
      "chickpeas",
      "potatoes",
      "cumin",
      "chili powder",
      "mint",
      "oil",
      "salt",
    ],
    cuisine: "Both",
    category: "Street Food",
    cookingTime: 30,
    servings: 4,
    spiceLevel: 3,
  },

  // ============ BREADS ============
  {
    name: "Naan",
    description:
      "Soft, pillowy leavened flatbread baked in a tandoor, brushed with butter — the essential curry companion.",
    ingredients: ["flour", "yeast", "yogurt", "sugar", "butter", "oil", "salt"],
    cuisine: "Both",
    category: "Bread",
    cookingTime: 25,
    servings: 6,
    spiceLevel: 1,
  },
  {
    name: "Roti",
    description:
      "Simple, wholesome unleavened flatbread made from whole wheat flour — the daily bread of the subcontinent.",
    ingredients: ["whole wheat flour", "water", "salt"],
    cuisine: "Both",
    category: "Bread",
    cookingTime: 15,
    servings: 6,
    spiceLevel: 1,
  },
  {
    name: "Paratha",
    description:
      "Flaky, layered flatbread enriched with ghee, pan-fried to golden perfection on a tawa.",
    ingredients: ["flour", "ghee", "oil", "salt"],
    cuisine: "Both",
    category: "Bread",
    cookingTime: 20,
    servings: 4,
    spiceLevel: 1,
  },
  {
    name: "Sheermal",
    description:
      "A sweet, saffron-infused Mughlai bread made with milk — traditionally served with nihari or kebabs.",
    ingredients: [
      "flour",
      "milk",
      "sugar",
      "saffron",
      "butter",
      "cardamom",
      "salt",
    ],
    cuisine: "Pakistani",
    category: "Bread",
    cookingTime: 30,
    servings: 4,
    spiceLevel: 1,
  },

  // ============ DESSERTS ============
  {
    name: "Gulab Jamun",
    description:
      "Soft, golden milk-dough balls soaked in fragrant rose and cardamom sugar syrup.",
    ingredients: [
      "khoya",
      "flour",
      "sugar",
      "cardamom",
      "rose water",
      "oil",
    ],
    cuisine: "Both",
    category: "Dessert",
    cookingTime: 40,
    servings: 6,
    spiceLevel: 1,
  },
  {
    name: "Jalebi",
    description:
      "Bright orange, crispy spirals of fermented batter soaked in saffron-scented sugar syrup.",
    ingredients: [
      "flour",
      "yogurt",
      "sugar",
      "saffron",
      "lemon",
      "oil",
    ],
    cuisine: "Both",
    category: "Dessert",
    cookingTime: 30,
    servings: 6,
    spiceLevel: 1,
  },
  {
    name: "Kheer",
    description:
      "A creamy rice pudding simmered slowly in milk with cardamom, sugar, and garnished with nuts.",
    ingredients: [
      "basmati rice",
      "milk",
      "sugar",
      "cardamom",
      "almonds",
      "pistachios",
    ],
    cuisine: "Both",
    category: "Dessert",
    cookingTime: 45,
    servings: 6,
    spiceLevel: 1,
  },
  {
    name: "Rasgulla",
    description:
      "Soft, spongy cottage cheese balls soaked in light sugar syrup — a Bengali classic.",
    ingredients: ["chhena", "sugar", "rose water", "cardamom"],
    cuisine: "Indian",
    category: "Dessert",
    cookingTime: 35,
    servings: 6,
    spiceLevel: 1,
  },
  {
    name: "Barfi",
    description:
      "Dense, fudge-like milk confection flavored with cardamom and topped with silver leaf.",
    ingredients: ["milk powder", "sugar", "ghee", "cardamom", "pistachios"],
    cuisine: "Both",
    category: "Dessert",
    cookingTime: 30,
    servings: 8,
    spiceLevel: 1,
  },

  // ============ BREAKFAST ============
  {
    name: "Halwa Puri",
    description:
      "A classic Pakistani breakfast trio of golden semolina halwa, crispy fried puri, and spiced chickpea curry.",
    ingredients: [
      "semolina",
      "flour",
      "chickpeas",
      "sugar",
      "ghee",
      "onions",
      "tomatoes",
      "cumin",
      "chili powder",
      "oil",
      "salt",
    ],
    cuisine: "Pakistani",
    category: "Breakfast",
    cookingTime: 45,
    servings: 4,
    spiceLevel: 2,
  },
  {
    name: "Aloo Paratha",
    description:
      "Whole wheat flatbread stuffed with spiced mashed potatoes, pan-fried with butter until golden and crispy.",
    ingredients: [
      "whole wheat flour",
      "potatoes",
      "onions",
      "green chilies",
      "coriander",
      "cumin",
      "butter",
      "salt",
    ],
    cuisine: "Both",
    category: "Breakfast",
    cookingTime: 30,
    servings: 4,
    spiceLevel: 2,
  },
  {
    name: "Dosa",
    description:
      "A crispy, golden crepe made from fermented rice and lentil batter — a South Indian breakfast staple.",
    ingredients: [
      "rice",
      "urad dal",
      "fenugreek seeds",
      "oil",
      "salt",
    ],
    cuisine: "Indian",
    category: "Breakfast",
    cookingTime: 25,
    servings: 4,
    spiceLevel: 1,
  },
];

async function seed() {
  await mongoose.connect(MONGO_URI);
  console.log("Connected to MongoDB");

  await Recipe.deleteMany({});
  console.log("Cleared existing recipes");

  await Recipe.insertMany(recipes);
  console.log(`Seeded ${recipes.length} recipes`);

  await mongoose.disconnect();
  console.log("Done");
}

seed().catch(console.error);
